# Generated by Django 3.2 on 2021-04-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_datetime', models.DateTimeField(verbose_name='order datetime')),
                ('order_id', models.CharField(max_length=40)),
                ('cl_ord_id', models.CharField(max_length=40)),
                ('symbol', models.CharField(max_length=7)),
                ('side', models.CharField(max_length=4)),
                ('order_type', models.CharField(max_length=20)),
                ('price_ep', models.IntegerField(verbose_name='scaled order price')),
                ('order_qty', models.IntegerField(verbose_name='order quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_datetime', models.DateTimeField(verbose_name='trade datetime')),
                ('symbol', models.CharField(max_length=7)),
                ('size', models.IntegerField(default=0)),
                ('closed_pnl', models.FloatField(default=0.0)),
                ('exchange_fee', models.FloatField(default=0.0)),
                ('funding_fee', models.FloatField(default=0.0)),
                ('realised_pnl', models.FloatField(default=0.0)),
            ],
        ),
    ]
